### ISSUE TITLE
bug with abort_err

### ISSUE THREAD

**Issue by Crowny23** [hmes98318/Music-Disc#19]
`**Describe` the bug**
AbortError: The operation was aborted
    at EventTarget.abortListener (node:events:958:14)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at EventTarget.dispatchEvent (node:internal/event_target:677:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at Timeout.<anonymous> (/home/crowny/Documents/botDisc/Music-Disc/node_modules/@discordjs/voice/dist/index.js:2504:39)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at new DOMException (node:internal/per_context/domexception:53:5)
      at AbortController.abort (node:internal/abort_controller:336:18)
      at Timeout.<anonymous> (/home/crowny/Documents/botDisc/Music-Disc/node_modules/@discordjs/voice/dist/index.js:2504:39)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)
}

when i play, bot joined but don't play music and disconnect

**Comment by Crowny23** [comment]
ok now i don't have error but when bot starting to play music, he disconnect directely :(

**Comment by hmes98318** [comment]
Can you provide detailed logs?

**Comment by hmes98318** [comment]
umm... do other songs have the same result? Because if a song can't be played, the bot will skip it.
