### ISSUE TITLE
Cannot play youtube playlists anymore

### ISSUE THREAD

**Issue by CTLN7** [hmes98318/Music-Disc#54]
/play and youtube playlist link used to work and queue up all the songs but not anymore. It just gives ❌ | No results found.

**Comment by hmes98318** [comment]
Is there any detailed logs and lavalink node version ?

**Comment by CTLN7** [comment]
> Is there any detailed logs and lavalink node version ?

How can i access these? I just have the bot in my discord.

**Comment by hmes98318** [comment]
OK, I thought you selfhosted this Bot.  
I have restarted the Bot. If this problem still occurs again, please tell me and attach the error link.

**Comment by CTLN7** [comment]
Still broken, where exactly do i find this error link?
![image](https://github.com/user-attachments/assets/0006034f-9f3c-4712-9735-4740d6c78e19)

**Comment by hmes98318** [comment]
> Still broken, where exactly do i find this error link?

Yes, I meant the URL that caused the error.  
Maybe it's the guild cache failure that prevents it from running, I've refreshed the cache and using this URL it works.  

Is it just a specific URL that doesn't work or others too?

**Comment by CTLN7** [comment]
None seem to work.
Here is one of the playlists i tried and did not work
https://www.youtube.com/watch?v=kXYiU_JCYtU&list=PLFWxnx3Ig_DCiUbtLdWBCXLox1ufUCBtM

**Comment by hmes98318** [comment]
OK, after I restarted Lavalink, the original test playlist URL also became unusable.  
I guess youtube changed something causing the [youtube-source plugin](https://github.com/lavalink-devs/youtube-source/) to fail to parse.  
All we can do now is wait for the fix : (

<details>
  <summary>Detailed log output</summary>
  
```
lavalink_v4  | 2024-11-29T14:39:06.650Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=kXYiU_JCYtU&list=PLFWxnx3Ig_DCiUbtLdWBCXLox1ufUCBtM"
lavalink_v4  | 2024-11-29T14:39:06.681Z ERROR 1 --- [Lavalink] [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Failed to load track
lavalink_v4  |
lavalink_v4  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong while looking up the track.
lavalink_v4  |  at lavalink.server.util.LoadingKt.loadAudioItem(loading.kt:20) ~[classes!/:4.0.8]
lavalink_v4  |  at lavalink.server.player.AudioLoaderRestHandler.loadTracks(AudioLoaderRestHandler.kt:59) ~[classes!/:4.0.8]
lavalink_v4  |  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
lavalink_v4  |  at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
lavalink_v4  |  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-2.0.0.jar!/:2.0.0-release-341]
lavalink_v4  |  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-2.0.0.jar!/:2.0.0-release-341]
lavalink_v4  |  at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207) ~[kotlin-reflect-2.0.0.jar!/:2.0.0-release-341]
lavalink_v4  |  at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[kotlin-reflect-2.0.0.jar!/:2.0.0-release-341]
lavalink_v4  |  at org.springframework.web.method.support.InvocableHandlerMethod$KotlinDelegate.invokeFunction(InvocableHandlerMethod.java:334) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:252) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
lavalink_v4  |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.8.jar!/:6.1.8]
lavalink_v4  |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at lavalink.server.io.ResponseHeaderFilter.doFilterInternal(ResponseHeaderFilter.kt:17) ~[classes!/:4.0.8]
lavalink_v4  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.9.jar!/:6.1.9]
lavalink_v4  |  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101) ~[undertow-servlet-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859) ~[undertow-core-2.3.13.Final.jar!/:2.3.13.Final]
lavalink_v4  |  at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
lavalink_v4  |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
lavalink_v4  |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
lavalink_v4  |  at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
lavalink_v4  |  at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink_v4  | Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video cannot be loaded.
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:235) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:183) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:423) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:154) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.player.AudioPlayerManager.loadItemSync(AudioPlayerManager.java:127) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at lavalink.server.util.LoadingKt.loadAudioItem(loading.kt:15) ~[classes!/:4.0.8]
lavalink_v4  |  ... 65 common frames omitted
lavalink_v4  | Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for playlist response: 400
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadPlaylistResult(NonMusicClient.java:215) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadPlaylist(NonMusicClient.java:413) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.YoutubeAudioSourceManager.lambda$getRouter$2(YoutubeAudioSourceManager.java:276) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:217) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  ... 71 common frames omitted
lavalink_v4  |  Suppressed: dev.lavalink.youtube.ClientInformation:
lavalink_v4  |   yts.version: 1.8.3
lavalink_v4  |   client.identifier: WEB
lavalink_v4  |   client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}
lavalink_v4  | Caused by: java.io.IOException: Invalid status code for playlist response: 400
lavalink_v4  |  at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.2.2.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadJsonResponse(NonMusicClient.java:67) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadPlaylistResult(NonMusicClient.java:213) ~[youtube-plugin-1.8.3.jar!/:na]
lavalink_v4  |  ... 74 common frames omitted
lavalink_v4  |
```
</details>

**Comment by hmes98318** [comment]
youtube-source v1.11.3 fixed.
